{
    'name': 'Industrial Menu Management',
    'version': '1.0',
    'depends': ['base', 'stock', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'security/industrial_menu_security.xml',
        'views/menu_cycle_views.xml',
        'views/menu_item_views.xml',
        'views/recipe_views.xml',
        'views/ingredient_views.xml',
        'views/nutritional_info_views.xml',
        'views/portion_views.xml',
        'views/inventory_views.xml',
        'views/menu_templates.xml',
        'data/menu_cycle_data.xml',
        'data/ingredient_data.xml',
        'reports/nutritional_report.xml',
        'reports/cost_report.xml',
    ],
    'installable': True,
    'application': True,
    'odoo_version': '18.0',
}